title: ProjectX
description: ProjectX is cool
url: "http://localhost:4000"
baseurl: /jekyll-codetabs/

markdown: kramdown

exclude:
  - README.md
  - serve.sh
  - build.sh
  - lib

sass:
  sass_dir: _sass
  style: compressed
